name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version number (e.g., 3.0.0)"
        required: true
      changelog:
        description: "The changelog for this version"
        required: true

env:
  FORCE_COLOR: true

jobs:
  create-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ github.event.inputs.version }}" || echo "Tag creation failed (possibly already exists)."
          git push origin "v${{ github.event.inputs.version }}" || echo "Tag push failed (possibly already exists)."

  build_windows:
    runs-on: windows-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "__version__ = '${{ github.event.inputs.version }}'" > _version.py

      - name: Build Executable
        run: |
          python -m nuitka `
            --assume-yes-for-downloads `
            --standalone `
            --onefile `
            --enable-plugin=pyside6 `
            --windows-icon-from-ico=streamkey.ico `
            --windows-console-mode=disable `
            --include-module=seleniumwire `
            --include-module=blinker._saferef `
            --include-package-data=seleniumwire `
            --include-package=certifi `
            --nofollow-import-to="*.tests" `
            --nofollow-import-to="pydoc" `
            --nofollow-import-to="test" `
            --windows-company-name="Suntury" `
            --windows-product-name="TikTok StreamKey | Generator" `
            --windows-file-description="TikTok Stream Key Generator for OBS Studio" `
            --windows-file-version="${{ github.event.inputs.version }}" `
            --windows-product-version="${{ github.event.inputs.version }}" `
            --output-dir=dist `
            main.py

      - name: Compress Executable
        run: Compress-Archive -Path dist/main.exe -DestinationPath TikTokStreamKeyGenerator-windows-${{ github.event.inputs.version }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: TikTokStreamKeyGenerator-windows-${{ github.event.inputs.version }}.zip

  build_macos:
    runs-on: macos-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "__version__ = '${{ github.event.inputs.version }}'" > _version.py

      - name: Build Executable
        run: |
          nuitka \
            --assume-yes-for-downloads \
            --standalone \
            --onefile \
            --enable-plugin=pyside6 \
            --include-module=seleniumwire \
            --include-module=blinker._saferef \
            --include-package-data=seleniumwire \
            --include-package=certifi \
            --nofollow-import-to="*.tests" \
            --nofollow-import-to="pydoc" \
            --nofollow-import-to="test" \
            --output-dir=dist \
            main.py

      - name: Compress Executable
        run: |
          zip -j TikTokStreamKeyGenerator-macos-${{ github.event.inputs.version }}.zip dist/main.app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: TikTokStreamKeyGenerator-macos-${{ github.event.inputs.version }}.zip

  build_linux:
    runs-on: ubuntu-22.04
    needs: create-tag
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache python3-pip zip python3-distutils
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          echo "__version__ = '${{ github.event.inputs.version }}'" > _version.py

      - name: Build Executable
        run: |
          nuitka \
            --assume-yes-for-downloads \
            --standalone \
            --onefile \
            --enable-plugin=pyside6 \
            --include-module=seleniumwire \
            --include-module=blinker._saferef \
            --include-package-data=seleniumwire \
            --include-package=certifi \
            --nofollow-import-to="*.tests" \
            --nofollow-import-to="pydoc" \
            --nofollow-import-to="test" \
            --output-dir=dist \
            main.py

      - name: Compress Executable
        run: |
          zip -j TikTokStreamKeyGenerator-linux-${{ github.event.inputs.version }}.zip dist/main.bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: TikTokStreamKeyGenerator-linux-${{ github.event.inputs.version }}.zip

  release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows, build_macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create the release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          body: ${{ github.event.inputs.changelog }}
          files: "artifacts/**/*.zip"